export const moviedata = [
    {id: 1, title: "Game of Thrones", description:'In the mythical continent of Westeros, several powerful families fight for control of the Seven Kingdoms. As conflict erupts in the kingdoms of men, an ancient enemy rises once again to threaten them all. Meanwhile, the last heirs of a recently usurped dynasty plot to take back their homeland from across the Narrow Sea.', posterURL:'https://i.pinimg.com/736x/69/44/1a/69441ab335f81915cbcae988a03ce2f6.jpg',trailer:<iframe width="731" height="411" src="https://www.youtube.com/embed/KPLWWIOCOOQ" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>, rating:'5'},
    {id: 2, title: "La Casa de Papel", description:"This original Netflix series, originally titled La Casa de Papel, follows the Professor (Álvaro Morte), a criminal mastermind who brings eight thieves together to take hostages and lock themselves in the Royal Mint of Spain as he manipulates the police to carry out his plan.", posterURL:'https://i.pinimg.com/originals/46/84/de/4684de7e080ee747bffbb5fedf43ede0.jpg', trailer:<iframe width="731" height="411" src="https://www.youtube.com/embed/_yJxbWKN3zE" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>,rating:'4.6'},
    {id: 3, title: "Peaky Blinders", description:'Birmingham, UK, 1919. In the aftermath of WW1, the Shelby family are making a name for themselves as bookmakers, racketeers and gangsters. Nominally the head of the family is the oldest brother, Arthur, but the real brains, ambition and drive in the organisation lies with Tommy, the second oldest. He will carve out an empire for himself that will stretch beyond Birmingham. This with the aid of his family and his gang, the Peaky Blinders.', posterURL:'https://i.pinimg.com/736x/a0/5a/27/a05a27c4e58d658605e1e92f4bc5cf65.jpg',trailer:<iframe width="731" height="411" src="https://www.youtube.com/embed/zxRwTERrAeM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>, rating:'4.8'},
    {id: 4, title: "Vikings", description:"The story of how Ragnar Lothbrok, a Norse farmer with a thirst for exploration, who becomes the king of the northmen. Lothbrok, clouded by ambition and an urge to attain supremacy leads his men and his family to glory in the historic lands of Britain and France.", posterURL:'https://i.pinimg.com/originals/05/3c/34/053c341838e4a28af8189e72b2b482a5.png',trailer:<iframe width="731" height="411" src="https://www.youtube.com/embed/9GgxinPwAGc" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>, rating:'4'},
    {id: 5, title: "The Revenant ", description:'Set in 1820s America, fur trapper and Frontiersman Hugh Glass struggles to survive the harsh winter after an oppressive Ree Indian attack and a mauling from a hostile maternal bear. Abandoned by his crew, Glass attempts to cross the bleak wasteland with only a single notion set in his mind; Revenge.', posterURL:'https://i.pinimg.com/originals/bf/2f/b1/bf2fb191552fb1d8b36291642a95243c.png',trailer:<iframe width="731" height="411" src="https://www.youtube.com/embed/LoebZZ8K5N0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>, rating:'3.8'},
    {id: 6, title: "The Godfather", description:"Michael, the young and idealistic son of Vito Corleone, the head of the most powerful Mafia clan in New York, returns home as a war hero and is determined to live his own life. But tragic circumstances make him face the legacy of his family.", posterURL:'https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UY1200_CR107,0,630,1200_AL_.jpg',trailer:<iframe width="731" height="411" src="https://www.youtube.com/embed/sY1S34973zA" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>, rating:'4.5'},
    {id: 7, title: "Train to Busan", description:'TRAIN TO BUSAN is a harrowing zombie horror-thriller that follows a group of terrified passengers fighting their way through a countrywide viral outbreak while trapped on a suspicion-filled, blood-drenched bullet train ride to Busan, a southern resort city that has managed to hold off the zombie hordes... or so everyone hopes.', posterURL:'https://www.themoviedb.org/t/p/original/4JlPE6un7uuy7iXMNXohxKtjD2A.jpg',trailer:<iframe width="731" height="411" src="https://www.youtube.com/embed/pyWuHv2-Abk" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>, rating:'2.5'},
    {id: 8, title: "IceAge:Continental Drift", description:'Manny, Diego, and Sid embark upon another adventure after their continent is set adrift. Using an iceberg as a ship, they encounter sea creatures and battle pirates as they explore a new world.', posterURL:'https://picfiles.alphacoders.com/366/366650.jpg',trailer:<iframe width="836" height="355" src="https://www.youtube.com/embed/xz-KgMtU_BM" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>, rating:'4.8'},
    {id: 9, title: "The Irishman", description:'In the 1950s, truck driver Frank Sheeran gets involved with Russell Bufalino and his Pennsylvania crime family. As Sheeran climbs the ranks to become a top hit man, he also goes to work for Jimmy Hoffa -- a powerful Teamster tied to organized crime.', posterURL:'https://images-na.ssl-images-amazon.com/images/I/71Y5pMAw8rL._AC_SL1200_.jpg',trailer:<iframe width="731" height="411" src="https://www.youtube.com/embed/WHXxVmeGQUc" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>, rating:'3.9'},
]
   
 
