export const moviedata = [
    {id: Math.random(), title: "Game of Thrones", description:'Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia', posterURL:'https://i.pinimg.com/736x/69/44/1a/69441ab335f81915cbcae988a03ce2f6.jpg',trailer:'', rating:'5'},
    {id: Math.random(), title: "La Casa de Papel", description:'An unusual group of robbers attempt to carry out the most perfect robbery in Spanish history - stealing 2.4 billion euros from the Royal Mint of Spain.', posterURL:'https://i.pinimg.com/originals/46/84/de/4684de7e080ee747bffbb5fedf43ede0.jpg', trailer:'',rating:'4.6'},
    {id: Math.random(), title: "Peaky Blinders", description:'A gangster family epic set in 19s England, centering on a gang who sew razor blades in the peaks of their caps, and their fierce boss Tommy Shelby', posterURL:'https://i.pinimg.com/736x/a0/5a/27/a05a27c4e58d658605e1e92f4bc5cf65.jpg',trailer:'', rating:'4.8'},
    {id: Math.random(), title: "Vikings", description:"Vikings tells the saga of Ragnar's band of Viking brothers and his family as he rises to become King of the Viking tribes.", posterURL:'https://i.pinimg.com/originals/05/3c/34/053c341838e4a28af8189e72b2b482a5.png',trailer:'', rating:'4'},
    {id: Math.random(), title: "The Revenant ", description:'A frontiersman on a fur trading expedition in 1820s fights for survival after being mauled by a bear and left for dead by members of his own hunting team', posterURL:'https://i.pinimg.com/originals/bf/2f/b1/bf2fb191552fb1d8b36291642a95243c.png',trailer:'', rating:'3.8'},
    {id: Math.random(), title: "The Godfather", description:"An organized crime dynasty's aging patriarch transfers control of his clandestine empire to his reluctant son ", posterURL:'https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UY1200_CR107,0,630,1200_AL_.jpg',trailer:'', rating:'4.5'},
    {id: Math.random(), title: "Train to Busan", description:'While a zombie virus breaks out in South Korea, passengers struggle to survive on the train from Seoul to Busan.', posterURL:'https://www.themoviedb.org/t/p/original/4JlPE6un7uuy7iXMNXohxKtjD2A.jpg',trailer:'', rating:'2.5'},
    {id: Math.random(), title: "IceAge:Continental Drift", description:'Manny,Diego,Sid embark upon another adventure after their continent is set adrift. Using an iceberg as a ship,they encounter sea creatures,battle pirates as explore new world.', posterURL:'https://picfiles.alphacoders.com/366/366650.jpg',trailer:'', rating:'4.8'},
    {id: Math.random(), title: "The Irishman", description:'Frank Sheeran(De Niro),a truck driver who becomes a hitman involved with mobster Russell Bufalino and his crime family, including his time working for the Teamster Jimmy Hoffa', posterURL:'https://images-na.ssl-images-amazon.com/images/I/71Y5pMAw8rL._AC_SL1200_.jpg',trailer:'', rating:'3.9'},
]
   
 
