export const moviedata = [
    {id: Math.random(), title: "Game of Thrones", description:'Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia', posterURL:'https://m.media-amazon.com/images/M/MV5BYTRiNDQwYzAtMzVlZS00NTI5LWJjYjUtMzkwNTUzMWMxZTllXkEyXkFqcGdeQXVyNDIzMzcwNjc@._V1_.jpg', rating:'5'},
    {id: Math.random(), title: "La Casa de Papel", description:'An unusual group of robbers attempt to carry out the most perfect robbery in Spanish history - stealing 2.4 billion euros from the Royal Mint of Spain.', posterURL:'https://i.pinimg.com/originals/46/84/de/4684de7e080ee747bffbb5fedf43ede0.jpg', rating:'4.6'},
    {id: Math.random(), title: "Peaky Blinders", description:'A gangster family epic set in 19s England, centering on a gang who sew razor blades in the peaks of their caps, and their fierce boss Tommy Shelby', posterURL:'https://postermega.com/p/1/b/a/1bade22301eab9a5718f2e1973e5010f_720.jpg', rating:'4.8'},
    {id: Math.random(), title: "Vikings", description:"Vikings tells the saga of Ragnar's band of Viking brothers and his family as he rises to become King of the Viking tribes.", posterURL:'https://starzplay-img-prod-ssl.akamaized.net/474w/MGM/VIKINGSY2013S05E011/VIKINGSY2013S05E011-474x677-PST.jpg', rating:'4'},
    {id: Math.random(), title: "The Revenant ", description:'A frontiersman on a fur trading expedition in 1820s fights for survival after being mauled by a bear and left for dead by members of his own hunting team', posterURL:'https://m.media-amazon.com/images/M/MV5BMDE5OWMzM2QtOTU2ZS00NzAyLWI2MDEtOTRlYjIxZGM0OWRjXkEyXkFqcGdeQXVyODE5NzE3OTE@._V1_.jpg', rating:'3.8'},
    {id: Math.random(), title: "The Godfather", description:"An organized crime dynasty's aging patriarch transfers control of his clandestine empire to his reluctant son ", posterURL:'https://m.media-amazon.com/images/M/MV5BM2MyNjYxNmUtYTAwNi00MTYxLWJmNWYtYzZlODY3ZTk3OTFlXkEyXkFqcGdeQXVyNzkwMjQ5NzM@._V1_UY1200_CR107,0,630,1200_AL_.jpg', rating:'4.5'},
    {id: Math.random(), title: "Now You See Me", description:'An F.B.I. Agent and an Interpol Detective track a team of illusionists who pull off bank heists during their performances, and reward their audiences with the money', posterURL:'https://m.media-amazon.com/images/M/MV5BMTY0NDY3MDMxN15BMl5BanBnXkFtZTcwOTM5NzMzOQ@@._V1_.jpg', rating:'2.5'},
    {id: Math.random(), title: "The Irishman", description:'Frank Sheeran (De Niro),a truck driver who becomes a hitman involved with mobster Russell Bufalino (Pesci) and his crime family, including his time working for the Teamster Jimmy Hoffa (Pacino)', posterURL:'https://images-na.ssl-images-amazon.com/images/I/71Y5pMAw8rL._AC_SL1200_.jpg', rating:'3.9'},
    {id: Math.random(), title: "Ice Age:Continental Drift", description:'Manny, Diego, and Sid embark upon another adventure after their continent is set adrift. Using an iceberg as a ship, they encounter sea creatures and battle pirates as they explore a new world.', posterURL:'https://m.media-amazon.com/images/M/MV5BMTM3NDM5MzY5Ml5BMl5BanBnXkFtZTcwNjExMDUwOA@@._V1_.jpg', rating:'4.8'},
]
   
 
